service: graphql-lambda


provider:
  name: aws
  runtime: nodejs12.x


package:
  excludeDevDependencies: true
  individually: true


plugins:
    - serverless-offline


functions:
  graphql:
    handler: handler.server
    events:
    - http:
        path: /
        method: post
        cors: true

  playground:
    handler: handler.playground
    events:
    - http:
        path: /
        method: get
        cors: true
